#!/bin/bash
#
# télécharger un pdf depuis sci-hub

destination=$HOME/downloads/scihub

if ! [ -d $destination ]; then
	mkdir $destination
fi

# regrouper tous les arguments
# regrouper les arguments dans une liste
args=("$@")
# nombre d'arguments
ELEMENTS=${#args[@]}
# echo chaque element dans une liste
# for loop
for (( i=0;i<$ELEMENTS;i++)); do
    #echo -n ${args[${i}]}"\ "
    concatener=$(echo $concatener" ")$(echo -n ${args[${i}]}"\ ")
done

concatener=$(echo $concatener | sed 's/\\//g')

site=$(curl -s -LH "" "https://sci-hub.now.sh/" | grep -i https://sci-hub...)
site=$(echo "$site" | grep -io https://sci-hub... | tail -n 1)
#echo $site
if [[ 'ping $(echo $site | cut -c9-100) | grep -io inconnu' = "inconnu" ]]; then
	echo "Sci-Hub introuvable."
	$(exec $BROWSER "https://sci-hub.now.sh/")
elif ! [[ $(echo "$concatener") = "" ]]; then
	#$(echo "$concatener" | sed 's/\///')
	recherche=$(echo $concatener | sed "s/'/\ /g" | sed 's/\ /+/g' | iconv -f utf8 -t ascii//TRANSLIT)
	if [[ $(echo $(curl -s "https://search.crossref.org/?q=$recherche") | grep -io "$concatener" | head -n 1) = "$concatener" ]]; then
		echo "Title found on Crossref."
		echo "Looking for DOI."
		doi=$(echo $(curl -s "https://search.crossref.org/?q=$recherche" | grep -io "https://doi.*" | grep -io "doi.*" | sed 's/http:\/\///' | grep -io "/.*" | sed 's/\///' | head -n 2 | tail -n 1))
		if [[ $(echo $doi | grep -io "doi:") = "doi:" || $(echo $doi | grep -io "doi.") = "doi." ]]; then
			echo ""
			echo "DOI for "$concatener" found : $doi"
			echo ""
			doi=$(echo $doi | sed 's/http:\/\///' | grep -io "/.*" | sed 's/\///')
		fi

	#echo $(curl -s $site/$doi) | grep -io "<iframe\ src\ =\ \"https.*\.pdf" | sed 's/<iframe\ src\ \=\ \"//'
	lien_telechargement=$(echo $(curl -s $site/$doi) | grep -io "<iframe\ src\ =\ \"https.*\.pdf" | sed 's/<iframe\ src\ \=\ \"//')
	nom_fichier=$(echo $lien_telechargement | sed 's:.*/::')
	#echo $nom_fichier
	cd $destination
	echo "Downloading '$nom_fichier' to '$destination'."
	curl -s "$lien_telechargement" --output "$nom_fichier"
	echo "Done."
	fi
else
	$BROWSER "$site"
fi

exit

