.TH SCITOPDF 1 scitopdf
.SH NAME
scitopdf \- bash script to fetch, download and auto-open papers from Sci-Hub
.SH SYNOPSIS
.B scitopdf
[ -l
.I FILE_LIST
]
[
.I TITLE
]
.SH DESCRIPTION
.B scitopdf
automatically downloads papers from Sci-Hub (website automatically found) based either on their title, url, author, date of publication (leveraging Crossref's search engine), or DOI.
.SH COMMANDS
.TP
.B -l
or
.B --list
look inside a file containing one reference by line to download them all
.SH AUTHORS
Written by dougy147 originally in 2020.
.SH LICENSE
GPLv3
