.TH SCITOPDF 1 scitopdf
.SH NAME
scitopdf \- auto-download pdf from Sci-Hub
.SH SYNOPSIS
.B scitopdf
[ -l
.I FILE_LIST
]
[
.I TITLE
]
.SH DESCRIPTION
.B scitopdf
takes a user email account and sets up a terminal-based email interface for it with
.SH COMMANDS
.TP
.B -l
look inside a file containing one reference by line to download them all
.SH AUTHORS
Written by dougy147 originally in 2020.
.SH LICENSE
GPLv3
